{"name": "test_ConsultationOrders[2020-02-1]", "status": "broken", "statusDetails": {"message": "yaml.parser.ParserError: while parsing a flow mapping\n  in \"../api/api.yaml\", line 131, column 9\nexpected ',' or '}', but got '{'\n  in \"../api/api.yaml\", line 133, column 24", "trace": "cls = <class 'gm.testcase.test_api.Test_api'>\n\n    @classmethod\n    def setup_class(cls):\n>       cls.login = Testapi().login()\n\ntest_api.py:14: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n../api/api_face.py:16: in __init__\n    self.data = self.api_load(\"../api/api.yaml\")\n../api/base_api.py:33: in api_load\n    return self.yaml_load(path)\n../api/base_api.py:29: in yaml_load\n    return yaml.safe_load(f)\n/usr/local/lib/python3.7/site-packages/yaml/__init__.py:162: in safe_load\n    return load(stream, SafeLoader)\n/usr/local/lib/python3.7/site-packages/yaml/__init__.py:114: in load\n    return loader.get_single_data()\n/usr/local/lib/python3.7/site-packages/yaml/constructor.py:49: in get_single_data\n    node = self.get_single_node()\n/usr/local/lib/python3.7/site-packages/yaml/composer.py:36: in get_single_node\n    document = self.compose_document()\n/usr/local/lib/python3.7/site-packages/yaml/composer.py:55: in compose_document\n    node = self.compose_node(None, None)\n/usr/local/lib/python3.7/site-packages/yaml/composer.py:84: in compose_node\n    node = self.compose_mapping_node(anchor)\n/usr/local/lib/python3.7/site-packages/yaml/composer.py:133: in compose_mapping_node\n    item_value = self.compose_node(node, item_key)\n/usr/local/lib/python3.7/site-packages/yaml/composer.py:84: in compose_node\n    node = self.compose_mapping_node(anchor)\n/usr/local/lib/python3.7/site-packages/yaml/composer.py:133: in compose_mapping_node\n    item_value = self.compose_node(node, item_key)\n/usr/local/lib/python3.7/site-packages/yaml/composer.py:84: in compose_node\n    node = self.compose_mapping_node(anchor)\n/usr/local/lib/python3.7/site-packages/yaml/composer.py:127: in compose_mapping_node\n    while not self.check_event(MappingEndEvent):\n/usr/local/lib/python3.7/site-packages/yaml/parser.py:98: in check_event\n    self.current_event = self.state()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <yaml.loader.SafeLoader object at 0x1024201d0>, first = False\n\n    def parse_flow_mapping_key(self, first=False):\n        if not self.check_token(FlowMappingEndToken):\n            if not first:\n                if self.check_token(FlowEntryToken):\n                    self.get_token()\n                else:\n                    token = self.peek_token()\n                    raise ParserError(\"while parsing a flow mapping\", self.marks[-1],\n>                           \"expected ',' or '}', but got %r\" % token.id, token.start_mark)\nE                   yaml.parser.ParserError: while parsing a flow mapping\nE                     in \"../api/api.yaml\", line 131, column 9\nE                   expected ',' or '}', but got '{'\nE                     in \"../api/api.yaml\", line 133, column 24\n\n/usr/local/lib/python3.7/site-packages/yaml/parser.py:550: ParserError"}, "parameters": [{"name": "year", "value": "'2020'"}, {"name": "month", "value": "'02'"}, {"name": "page", "value": "'1'"}], "start": 1588931570907, "stop": 1588931570907, "uuid": "ef2a8467-0ef6-4432-8c08-d463f3f92fbe", "historyId": "8c0b58a58d24727160223892e247adcc", "testCaseId": "7e2035bcb94ad5aceeb72d7504bc5366", "fullName": "test_api.Test_api#test_ConsultationOrders", "labels": [{"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "Test_api"}, {"name": "host", "value": "dengyingdeMacBook-Pro.local"}, {"name": "thread", "value": "4816-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api"}]}